[package]
name = "mweb-tangle"
version = "0.1.0"
authors = ["CrLF0710"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
anyhow = "1.0.13"
mweb = {path = "../mweb"}
